apiVersion: apps/v1
kind: Deployment
metadata:
  name: current-time-service
  labels:
    app: current-time-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: current-time-service
  template:
    metadata:
      labels:
        app: current-time-service
    spec:
      containers:
      - name: current-time-service
        image: akadirvel1/currenttimeservice:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
