apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-server
  namespace: dev-server
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: gitops-demo.com
      http:
        paths:
          - path: /swagger
            pathType: Prefix
            backend:
              service:
                name: dev-server
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dev-server
                port:
                  number: 80
