apiVersion: v1
kind: Service
metadata:
  name: dev-server
spec:
  selector:
    app: dev-server
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80          # Exposes port 80 externally
      targetPort: 8080   # The container is listening on port 8080
