apiVersion: v1
kind: Service
metadata:
  name: current-time-service
spec:
  type: LoadBalancer 
  selector:
    app: current-time-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
